config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :webhooks, only: [:create]

  post 'orders/create', to: 'orders#create'
  get 'success', to: 'orders#success'
  get 'cancel', to: 'orders#cancel'
  resources :orders

  post 'pictures/add_to_cart/:id', to: 'pictures#add_to_cart', as: 'add_to_cart'
  delete 'pictures/remove_from_cart/:id', to: 'pictures#remove_from_cart', as: 'remove_from_cart'
  resources :pictures
  
  get 'home', to: 'pages#home'
  get 'bio', to: 'pages#bio'
  get 'portfolio', to: 'pages#portfolio'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#create'
  resources :pages
  
  get '/dashboard', to: 'users#dashboard'
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

end  

app/models/user.rb
class User < ApplicationRecord

    has_many :order
    attr_accessor :remember_token

    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 250 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? 
        BCrypt::Engine::MIN_COST :
                                                      
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.authenticate(user_info)
        find_by_username_and_password(user_info[:email], user_info[:password])
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, 
        User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?
        (remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    after_create do
        customer = Stripe::Customer.create(email: :email)
        update(stripe_customer_id: user.id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]
    before_action :logged_in_user, only: %i[ edit update destroy ]
    before_action :correct_user, only: %i[ edit update ]
    before_action :admin_user, only: %i[ destroy index ]

    def dashboard
      @pictures = Picture.all
      @orders = Order.all
    end

    # GET /users or /users.json
    def index
      @users = User.all
    end
  
    # GET /users/1 or /users/1.json
    def show
      @user = User.find(params[:id])
    end
  
    # GET /users/new
    def new
      @user = User.new(user_params)
      
        if @user.save
          log_in @user
          flash[:success] = "Welcome to the Sample App!"
          redirect_to @user
        else
          render 'new'
          flash[:error] = "Unsuccessful save."
        end
      
    end
  
    # GET /users/1/edit
    def edit
    end
  
    
    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1 or /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    def login
      @user = User.new
      @user.email = params[:email]
    end
  
    def process_login
      if user = User.authenticate(params[:user])
        session[:id] = user.id
        redirect_to session[:return_to] || '/'
      else
        flash[:error] = 'Invalid login.'
        redirect_to :action => 'login', :username => params[:user][:username]
      end
    end
  
    def logout
      reset_session
      flash[:message] = 'Logged out.'
      redirect_to :action => 'login'
    end
    
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:name, :email, :password)
      end

      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
      end

      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end

      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
end
end

app/views/users/_form.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>



 

  <div class="actions">
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/dashboard.html.erb
    <ul class="orders">
        <% @orders.each do |order| %>
            <li>
                <%= order.product_id %>
                <%= order.user_id %>
                <%= order.status %>
                <%= order.error_message %>
                <%= order.customer_id %>
                <%= order.price_cents %>
                <%= order.created_at %>
            </li>
        <% end %>
    </ul>

<ul class="pictures">
        <% @pictures.each do |picture| %>
            <li>
                <%= picture.title %>
                <%= picture.description %>
                <%= picture.date %>
                <%= picture.location %>
                <%= picture.price %>
                <%= picture.created_at %>
            </li>
        <% end %>
    </ul>

<%= link_to "New Picture", new_picture_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<%=stylesheet_link_tag "login.css"%>
<div class="container">
<main class="form-signin">
  
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

  <%= form_with(url: login_path, scope: :session, local: true, method: "post") do |f| %>
    <div class="form-floating">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <div class="form-floating">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  
    <div class="checkbox mb-3">
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.checkbox :remember_me%>
        <span>Remember me on this computer</span>
      <% end %>
    </div>
    
    <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
    <p class="mt-5 mb-3 text-muted">&copy; 2021</p>
  
</main>
</div class="container">

    

app/views/users/new.html.erb
<%= stylesheet_link_tag "signup"%>
<div class="container">
    <h1>New User</h1>
</div>

<%= render 'form', user: @user %>

<div class="container">
    <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <aside class="col-md-4">    
    <section class="user_info">       
        <h1>
            <%= @user.name %>      
        </h1>    
    </section>  
    </aside>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>