config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :webhooks, only: [:create]

  post 'orders/create', to: 'orders#create'
  get 'success', to: 'orders#success'
  get 'cancel', to: 'orders#cancel'
  resources :orders

  post 'pictures/add_to_cart/:id', to: 'pictures#add_to_cart', as: 'add_to_cart'
  delete 'pictures/remove_from_cart/:id', to: 'pictures#remove_from_cart', as: 'remove_from_cart'
  resources :pictures
  
  get 'home', to: 'pages#home'
  get 'bio', to: 'pages#bio'
  get 'portfolio', to: 'pages#portfolio'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#create'
  resources :pages
  
  get '/dashboard', to: 'users#dashboard'
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

end  

app/models/picture.rb
class Picture < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true, length: { maximum: 50 }, uniqueness: true
    validates :description, presence: true, length: { maximum: 500 }, uniqueness: true
    validates :location, length: { maximum: 50 }

    has_many :order

    # transform shopping cart pictures into an array of line items
    def to_builder
        Jbuilder.new do |picture|
        picture.price stripe_price_id
        picture.quantity 1
        end
    end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  #before_action :admin_user, only: %i[ destroy create update index ]
  before_action :logged_in_user, only: %i[ add_to_cart remove_from_cart ]

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to products_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to products_path
  end

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show
    @picture = Picture.find(params[:id])
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)
    Stripe.api_key = Rails.application.credentials.dig(:stripe, :dev_private_key)
        product = Stripe::Product.create({name: params[:picture][:title], 
                                          description: params[:picture][:description], 
                                          #images: params[:picture][:image], 
                                          shippable: true})
        price = Stripe::Price.create({product: product.id, 
                                      unit_amount: @picture.price, 
                                      currency: @picture.currency})
        Picture.update(stripe_product_id: product.id, stripe_price_id: price.id)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:title, :description, :date, :location, :image, :price, :currency)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td><%= picture.date %></td>
        <td><%= picture.location %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @picture.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @picture.location %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>