config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :webhooks, only: [:create]

  post 'orders/create', to: 'orders#create'
  get 'success', to: 'orders#success'
  get 'cancel', to: 'orders#cancel'
  resources :orders

  post 'pictures/add_to_cart/:id', to: 'pictures#add_to_cart', as: 'add_to_cart'
  delete 'pictures/remove_from_cart/:id', to: 'pictures#remove_from_cart', as: 'remove_from_cart'
  resources :pictures
  
  get 'home', to: 'pages#home'
  get 'bio', to: 'pages#bio'
  get 'portfolio', to: 'pages#portfolio'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#create'
  resources :pages
  
  get '/dashboard', to: 'users#dashboard'
  get '/signup', to: 'users#new'
  get '/login', to: 'users#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

end  

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="text-center text-lg-start bg-light text-muted">
        <p class="text-center">Website created by Tristan Orndoff</p>
    </footer>
</div>

app/views/layouts/_navigation.html.erb
<div class="container_header">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="http://localhost:3000"/></svg>
        <span class="fs-4">Brower Designs</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="http://localhost:3000" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="http://localhost:3000/portfolio" class="nav-link">Portfolio</a></li>
        <li class="nav-item"><a href="http://localhost:3000/bio" class="nav-link">Bio</a></li>
        <li class="nav-item"><a href="http://localhost:3000/contact" class="nav-link">Contact</a></li>
        <li class="nav-item"><a href=<%=signup_path%> class="nav-link">Sign Up</a></li>
        <li class="nav-item"><a href=<%=login_path%> class="nav-link">Login</a></li>

      </ul>
    </header>
  </div>
  

app/views/layouts/_navigation2.html.erb
<div class="container_header">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4">Brower Designs</span>
      </a>


      <ul class="nav nav-pills">
        <li><%= link_to root_path, class: "nav-link" do%> <%= icon("house", class: "house-nav-link") %> <% end %></li>
        <li><%= link_to portfolio_path, class: "nav-link" do%> <%= icon("grid-3x3-gap-fill", class: "images-nav-link") %> <% end %></li>
        <li class="nav-item"><a href="http://localhost:3000/bio" class="nav-link">Bio</a></li>
        <li><%= link_to contact_path, class: "nav-link" do%> <%= icon("calendar-plus", class: "contact-nav-link") %> <% end %></li>
                <li><%= link_to logout_path, class: "nav-link" do%> <%= icon("box-arrow-right", class: "logout-nav-link") %> <% end %></li>
        
        
      </ul>
    </header>
  </div

app/views/layouts/_photoupload.html.erb
<%= form_for @picture do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :date %>
    <%= f.date_field :date %>    

    <%= f.label :picture %>
    <%= f.file_field :picture, accept: "image/png, image/jpeg" %>

    <%= f.submit%> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= yield(:title) %> | Brower Designs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if logged_in? %>
      <%= render 'layouts/navigation' %>
    <% else %>
      <%= render 'layouts/navigation2' %>
    <% end %>

    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%=message %>
    </div>
    <% end %>

    <%= stylesheet_link_tag 'navbar.css' %>
  </header>
  
  <div class="application-container">
    <body>
      <%= yield %>
    </body>
  </div>
  
  <footer>
    <%= render 'layouts/footer' %>
    <%= stylesheet_link_tag 'footer.css' %>
  </footer>

</html>